### ISSUE TITLE
初学者的问题

### ISSUE THREAD

**Issue by IPNUISTlegal** [nnUyi/SNGAN#3]
同学你好，我是深度学习的初学者。我想问下，把你所给输入图像大小改成256*256，输出图像也是同样大小。卷积核大小、个数需要改变吗？或者说程序中需要改动哪里？谢谢了

**Comment by nnUyi** [comment]
在main_sngan中把input_height, input_width修改成256, 然后你需要修改一下generator和discriminator，增加几层conv 和 pooling，因为这两个网络是根据64设计的，改成256在discriminator和最后的fully connected layer会很大，内存可能不够

**Comment by IPNUISTlegal** [comment]
谢谢你同学！现在神经网络好像都流行全卷积，全连接估计我也不会加。
